apiVersion: v1
kind: Pod
metadata:
  name: ny-taxi-exec
  namespace: emr-data-team-a
  labels:
    applicationId: ny-taxi-yunikorn
    queue: root.test # YuniKorn Queue
  annotations:
    yunikorn.apache.org/task-group-name: "spark-executor" # YuniKorn Gang Scheduling annotation

spec:
  volumes:
    - name: spark-local-dir-1
      hostPath:
        path: /local1
        type: Directory
    - name: spark-local-dir-2
      hostPath:
        path: /local2
        type: Directory

  nodeSelector:
    "NodeGroupType": "SparkMemoryOptimized"
    "topology.kubernetes.io/zone": "us-west-2b"

  containers:
    - name: spark-kubernetes-executor # Don't change this name. EMR on EKS looking for this name
      volumeMounts:
        - name: spark-local-dir-1
          mountPath: /data1
          readOnly: false
        - name: spark-local-dir-2
          mountPath: /data2
          readOnly: false

  tolerations:
    - key: "spark-memory-optimized"
      operator: "Exists"
      effect: "NoSchedule"
